

name: 'ft_surrogate'

kwargs:
  probability: 0.5
  phase_noise_magnitude: 0.2
  transform_type: 'additive'
  shuffle: False
  random_state: ${seed}
  classes: null

optimization_parameter: 'phase_noise_magnitude'
op_neutral_value: 0

search:
  strategy: 'range'
  start: ${augmentation.ft_surrogate.op_neutral_value}
  end: 1
  step: 0.1
  d_type: 'float'

visualisation_config:
  name: 'FT Surrogate'
  label: 'Phase noise magnitude'
  metric: 'balanced_accuracy'
  metric_label: 'Balanced Accuracy'
  kwargs:
    plot_type: 'boxplot'
    color: 'darkmagenta'
    boxplot_color: 'pink'
    percentage: True
    subject_display: True
    relative_to_baseline: True
    baseline_parameter_value: ${augmentation.ft_surrogate.op_neutral_value}
    parameter_rounding: 1
    metric_rounding: 4