

name: 'channels_dropout'

kwargs:
  probability: 0.5
  p_drop: 0.1
  transform_type: 'additive'
  shuffle: False
  random_state: ${seed}
  classes: null

optimization_parameter: 'p_drop'
search:
  strategy: 'range'
  start: 0
  end: 1
  step: 0.1
  d_type: 'float'

visualisation_config:
  name: 'Channels Dropout'
  label: 'Dropout Probability'
  metric: 'balanced_accuracy'
  metric_label: 'Balanced Accuracy'
  kwargs:
    plot_type: 'boxplot'
    color: 'darkorange'
    boxplot_color: 'bisque'
    percentage: True
    subject_display: True
    relative_to_baseline: True
    baseline_parameter_value: ${augmentation.channels_dropout.search.start}
    parameter_rounding: 1
    metric_rounding: 4